# Generated by Django 4.2.8 on 2023-12-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_user_email_alter_user_id_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
