# Generated by Django 4.2.8 on 2023-12-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_alter_posts_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_user',
            fields=[
                ('id', models.IntegerField()),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
            ],
        ),
    ]
